version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    networks:
      - easy_paste_network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm run build && npm start"
    networks:
      - easy_paste_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - easy_paste_network

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: easy_paste
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - easy_paste_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin
    networks:
      - easy_paste_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  easy_paste_network:
    name: easy_paste_network
